### ISSUE TITLE
Keyboard Notification

### ISSUE THREAD

**Issue by asoong** [candostdagdeviren/CDAlertView#22]
Hey guys, just wanted to see if this was a bug or my usage was incorrect - is the AlertView supposed to adjust its frame in the event of a keyboard show notification like a UIAlertController? As soon as the keyboard comes up (I have `isTextFieldHidden` set to false), it covers the bottom of the alert (+ button). Thanks!

**Comment by candostdagdeviren** [comment]
Hello! It adjusts it's frame to make TextField visible only. It doesn't handle button covering or other things. It was the intent at first. Because users are able to make popup big and during such cases, it makes sense to resign textField by calling `textFieldResignFirstResponder()` method when user touched outside of UITextField or "Done" button on keyboard.

**Comment by candostdagdeviren** [comment]
I'm closing this issue. If you have any other questions, feel free to create a new issue :)
